# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "block_source_cc",
    hdrs = ["block_source.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "block_source_test",
    size = "small",
    srcs = ["block_source_test.cc"],
    deps = [
        ":block_source_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
