# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "string_interner_benchmark",
    testonly = True,
    srcs = ["string_interner_benchmark.cc"],
    tags = [
        "clang-tidy",
        "manual",
    ],
    deps = [
        ":container_string_index_cc",
        ":string_interner_cc",
        ":string_interner_map_cc",
        "//mbo/container/experimental/hamt:hamt_node_string_index_cc",
        "//mbo/container/experimental/hamt:hamt_string_index_cc",
        "//mbo/hash:hash_cc",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:node_hash_map",
        "@abseil-cpp//absl/strings",
        "@com_github_google_benchmark//:benchmark",
    ],
)

cc_library(
    name = "container_string_index_cc",
    hdrs = ["container_string_index.h"],
    visibility = ["//visibility:public"],
    deps = [":string_id_cc"],
)

cc_test(
    name = "container_string_index_test",
    size = "small",
    srcs = ["container_string_index_test.cc"],
    deps = [
        ":container_string_index_cc",
        ":string_id_cc",
        ":string_interner_cc",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:node_hash_map",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "string_interner_cc",
    hdrs = ["string_interner.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":arena_string_storage_cc",
        ":string_id_cc",
        "//mbo/config:require_cc",
        "//mbo/container:segmented_vector_cc",
        "//mbo/container/experimental/hamt:hamt_string_index_cc",
    ],
)

cc_test(
    name = "string_interner_test",
    size = "small",
    srcs = ["string_interner_test.cc"],
    deps = [
        ":string_id_cc",
        ":string_interner_cc",
        "//mbo/container:limited_vector_cc",
        "//mbo/hash:hash_cc",
        "//mbo/memory:arena_cc",
        "//mbo/memory:block_source_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "string_interner_require_exceptions_test",
    size = "small",
    srcs = ["string_interner_require_exceptions_test.cc"],
    copts = ["-fexceptions"] + select({
        "@rules_cc//cc/compiler:clang": ["-Wno-exceptions"],
        "//conditions:default": [],
    }),
    deps = [
        ":string_interner_cc",
        ":string_interner_map_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "string_interner_map_cc",
    hdrs = ["string_interner_map.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":string_interner_cc",
        "//mbo/container:segmented_vector_cc",
    ],
)

cc_test(
    name = "string_interner_map_test",
    size = "small",
    srcs = ["string_interner_map_test.cc"],
    deps = [
        ":string_interner_map_cc",
        "//mbo/container:limited_vector_cc",
        "//mbo/memory:arena_block_source_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "arena_string_storage_cc",
    hdrs = ["arena_string_storage.h"],
    visibility = ["//visibility:public"],
    deps = ["//mbo/memory:arena_cc"],
)

cc_test(
    name = "arena_string_storage_test",
    size = "small",
    srcs = ["arena_string_storage_test.cc"],
    deps = [
        ":arena_string_storage_cc",
        "//mbo/memory:arena_cc",
        "//mbo/memory:block_source_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "string_id_cc",
    hdrs = ["string_id.h"],
    visibility = ["//visibility:public"],
    deps = ["//mbo/types:strong_id_cc"],
)

cc_test(
    name = "string_id_test",
    size = "small",
    srcs = ["string_id_test.cc"],
    deps = [
        ":string_id_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
