#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0
"""Derive the SegmentedDeque timing and storage report from an immutable envelope."""

import argparse
import collections
import json
import math
import pathlib
import shlex
import statistics

import align_markdown_tables
import benchmark_artifact


def summarize(rows):
    """Keep raw repetitions, normalize units, and reject incomplete/mixed workloads."""
    groups = collections.defaultdict(list)
    for row in rows:
        if row.get("run_type", "iteration") != "iteration":
            continue
        groups[row.get("run_name", row["name"])].append(row)
    result = {}
    for name, samples in sorted(groups.items()):
        if len(samples) != 9 or sorted(row["repetition_index"] for row in samples) != list(range(9)):
            raise ValueError(f"{name}: expected nine distinct raw repetitions")
        work = {row["work_items"] for row in samples}
        if len(work) != 1 or next(iter(work)) <= 0:
            raise ValueError(f"{name}: inconsistent work-item normalization")
        factors = {"ns": 1, "us": 1_000, "ms": 1_000_000, "s": 1_000_000_000}
        times = sorted(row["cpu_time"] * factors[row["time_unit"]] for row in samples)
        if not all(math.isfinite(value) and value > 0 for value in times):
            raise ValueError(f"{name}: invalid timing")
        mean = statistics.mean(times)
        deviation = statistics.stdev(times)
        result[name] = {
            "minimum": times[0],
            "fast_three": statistics.mean(times[:3]),
            "median": statistics.median(times),
            "mean": mean,
            "sd": deviation,
            "cv": 100 * deviation / mean,
            "maximum": times[-1],
            "per_item": statistics.median(times) / next(iter(work)),
            "rows": samples,
        }
    if not result:
        raise ValueError("no raw repetitions")
    return result


def counter(samples, key):
    values = sorted({row[key] for row in samples if key in row})
    if not values:
        return "n/a"
    if len(values) == 1:
        return f"{values[0]:g}"
    return f"{values[0]:g}..{values[-1]:g}"


def toolchain_identity(toolchain):
    result = dict(toolchain)
    result["build_flags"] = [token for token in shlex.split(result.get("build_flags", ""))
                             if not token.startswith(("--benchmark_filter=", "--benchmark_out="))]
    return result


def render(envelope, artifact_name):
    envelopes = envelope if isinstance(envelope, list) else [envelope]
    names = artifact_name if isinstance(artifact_name, list) else [artifact_name]
    if len(envelopes) != len(names) or not envelopes:
        raise ValueError("each envelope needs an artifact name")
    envelope = envelopes[0]
    rows = []
    for item in envelopes:
        benchmark_artifact.validate(item)
        # Family filters differ; the compiler, build configuration, and host must match.
        left = toolchain_identity(item["toolchain"])
        right = toolchain_identity(envelope["toolchain"])
        if (item["git"]["commit"] != envelope["git"]["commit"] or left != right
                or item.get("controls") != envelope.get("controls")
                or item.get("build") != envelope.get("build")
                or any(item["host"][key] != envelope["host"][key]
                       for key in ("cpu_model", "architecture", "os"))):
            raise ValueError("envelopes must describe the same source, host CPU, and toolchain")
        rows.extend(item["google_benchmark"]["benchmarks"])
    summaries = summarize(rows)
    noisy = sum(value["cv"] > 10 for value in summaries.values())
    source = envelope["git"]["commit"]
    host = envelope["host"]
    toolchain = envelope["toolchain"]
    lines = [
        "# SegmentedDeque performance evidence", "",
        f"Source: `{source}`. Host: {host['cpu_model']}, {host['os']} {host['architecture']}.",
        f"Compiler: {toolchain['compiler_name']} {toolchain['compiler_version']}; "
        f"{toolchain['cxx_standard']}; {toolchain['standard_library']}; "
        f"Bazel {toolchain['bazel_version']}.", "",
        "Artifacts: " + ", ".join(f"[{name}]({name})" for name in names) + ". This report is generated by "
        "`tools/segmented_deque_report.py`; the raw JSON is authoritative.", "",
        "All timing columns use CPU nanoseconds per benchmark iteration. Fast 3 is the arithmetic "
        "mean of the fastest three of nine repetitions. SD is sample standard deviation; CV uses "
        "all nine. The per-item column divides the median by traversed elements, inserted elements, "
        "or queue pop/push pairs, as appropriate. Growth-event iterations contain one insertion.", "",
        f"{noisy} of {len(summaries)} families exceed 10% CV. "
        "These are repeated means, not tail-latency percentiles. "
        "Available-host evidence does not select a cross-platform tuning default.", "",
        "## Matched S256 comparisons", "",
        "Ratios are deque median divided by the baseline median for the same workload. "
        "Above 1 means the experimental deque takes longer. Missing operations are omitted.", "",
        "| Family | Deque ns/item | Vector ratio | Standard deque ratio | Deque CV |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for name, value in summaries.items():
        if not name.startswith("SegmentedDeque/S256/"):
            continue
        vector = summaries.get(name.replace("SegmentedDeque/", "SegmentedVector/", 1))
        standard = summaries.get(name.replace("SegmentedDeque/S256/", "StdDeque/", 1))
        if vector is None and standard is None:
            continue
        ratios = [f"{value['median'] / baseline['median']:.3f}" if baseline else "n/a"
                  for baseline in (vector, standard)]
        lines.append(f"| `{name}` | {value['per_item']:.3f} | {' | '.join(ratios)} | {value['cv']:.2f}% |")
    lines += ["", "## All timing families", "",
              "| Family | Min ns | Fast 3 ns | Median ns | Mean ns | Sample SD ns | CV | Max ns | Median ns/item |",
              "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for name, value in summaries.items():
        numbers = [f"{value[key]:.3f}" for key in ("minimum", "fast_three", "median", "mean", "sd")]
        lines.append(f"| `{name}` | {' | '.join(numbers)} | {value['cv']:.2f}% | "
                     f"{value['maximum']:.3f} | {value['per_item']:.3f} |")
    keys = ("container_bytes", "capacity", "segments", "source_bytes_reserved", "warm_allocations", "warm_allocated_bytes",
            "timed_allocations", "timed_deallocations", "event_allocations", "event_allocated_bytes",
            "event_deallocations")
    lines += ["", "## Storage and event counters", "",
              "Each cell is the common value across raw repetitions, or the observed min..max range. "
              "Missing counters are n/a; standard-container storage is not inferred.", "",
              "| Family | " + " | ".join(keys) + " |",
              "| --- | " + " | ".join("---:" for _ in keys) + " |"]
    for name, value in summaries.items():
        if not any(key in row for key in keys for row in value["rows"]):
            continue
        lines.append(f"| `{name}` | " + " | ".join(counter(value["rows"], key) for key in keys) + " |")
    return align_markdown_tables.align_text("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifact", type=pathlib.Path, nargs="+")
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()
    envelopes = [json.loads(path.read_text()) for path in args.artifact]
    args.output.write_text(render(envelopes, [path.name for path in args.artifact]))


if __name__ == "__main__":
    main()
