# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_fuzzing//fuzzing:cc_defs.bzl", "cc_fuzz_test")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "hamt_node_string_index_cc",
    hdrs = ["hamt_node_string_index.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":hamt_string_index_cc",
        "//mbo/container:hamt_node_map_cc",
    ],
)

cc_test(
    name = "hamt_node_string_index_test",
    size = "small",
    srcs = ["hamt_node_string_index_test.cc"],
    deps = [
        ":hamt_node_string_index_cc",
        ":string_interner_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "container_string_index_cc",
    hdrs = ["container_string_index.h"],
    visibility = ["//visibility:public"],
    deps = [":string_id_cc"],
)

cc_test(
    name = "container_string_index_test",
    size = "small",
    srcs = ["container_string_index_test.cc"],
    deps = [
        ":container_string_index_cc",
        ":string_id_cc",
        ":string_interner_cc",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:node_hash_map",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "string_interner_cc",
    hdrs = ["string_interner.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":arena_string_storage_cc",
        ":hamt_string_index_cc",
        ":string_id_cc",
        "//mbo/config:require_cc",
        "//mbo/container:segmented_sequence_cc",
    ],
)

cc_test(
    name = "string_interner_test",
    size = "small",
    srcs = ["string_interner_test.cc"],
    deps = [
        ":string_id_cc",
        ":string_interner_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "string_interner_require_exceptions_test",
    size = "small",
    srcs = ["string_interner_require_exceptions_test.cc"],
    copts = ["-fexceptions"] + select({
        "@rules_cc//cc/compiler:clang": ["-Wno-exceptions"],
        "//conditions:default": [],
    }),
    deps = [
        ":string_interner_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "hamt_string_index_cc",
    hdrs = ["hamt_string_index.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":string_id_cc",
        "//mbo/container:hamt_flat_map_cc",
    ],
)

cc_test(
    name = "hamt_string_index_test",
    size = "small",
    srcs = ["hamt_string_index_test.cc"],
    deps = [
        ":hamt_string_index_cc",
        ":string_id_cc",
        "//mbo/container:hamt_options_cc",
        "//mbo/memory:block_source_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "arena_string_storage_cc",
    hdrs = ["arena_string_storage.h"],
    visibility = ["//visibility:public"],
    deps = ["//mbo/memory:arena_cc"],
)

cc_test(
    name = "arena_string_storage_test",
    size = "small",
    srcs = ["arena_string_storage_test.cc"],
    deps = [
        ":arena_string_storage_cc",
        "//mbo/memory:arena_cc",
        "//mbo/memory:block_source_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "string_id_cc",
    hdrs = ["string_id.h"],
    visibility = ["//visibility:public"],
    deps = ["//mbo/types:strong_id_cc"],
)

cc_test(
    name = "string_id_test",
    size = "small",
    srcs = ["string_id_test.cc"],
    deps = [
        ":string_id_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "contains_cc",
    hdrs = ["contains.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "contains_test",
    size = "small",
    srcs = ["contains_test.cc"],
    deps = [
        ":contains_cc",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "indent_cc",
    srcs = ["indent.cc"],
    hdrs = ["indent.h"],
    implementation_deps = [
        "@abseil-cpp//absl/strings",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "indent_test",
    size = "small",
    srcs = ["indent_test.cc"],
    deps = [
        ":indent_cc",
        "//mbo/testing:matchers_cc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "numbers_cc",
    hdrs = ["numbers.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//mbo/container:limited_map_cc",
    ],
)

cc_test(
    name = "numbers_test",
    size = "small",
    srcs = ["numbers_test.cc"],
    deps = [
        ":numbers_cc",
        "@abseil-cpp//absl/strings:str_format",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "parse_cc",
    srcs = ["parse.cc"],
    hdrs = ["parse.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//mbo/status:status_macros_cc",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "parse_test",
    size = "small",
    srcs = ["parse_test.cc"],
    deps = [
        ":parse_cc",
        "//mbo/status:status_macros_cc",
        "//mbo/testing:status_cc",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_fuzz_test(
    name = "parse_fuzz_test",
    size = "small",
    srcs = ["parse_fuzz_test.cc"],
    deps = [":parse_cc"],
)

cc_library(
    name = "split_cc",
    hdrs = ["split.h"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "split_test",
    size = "small",
    srcs = ["split_test.cc"],
    deps = [
        ":split_cc",
        "//mbo/types:traits_cc",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "strip_cc",
    srcs = ["strip.cc"],
    hdrs = ["strip.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":parse_cc",
        "//mbo/status:status_macros_cc",
        "//mbo/testing:status_cc",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "strip_test",
    size = "small",
    srcs = ["strip_test.cc"],
    deps = [
        ":strip_cc",
        "//mbo/status:status_macros_cc",
        "//mbo/testing:matchers_cc",
        "//mbo/testing:status_cc",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
